{"trial_id": "0049", "hyperparameters": {"space": [{"class_name": "Choice", "config": {"name": "activation_layer_0", "default": "relu", "conditions": [], "values": ["relu", "leaky_relu", "tanh", "elu", "selu", "exponential", "softmax", "softplus"], "ordered": false}}, {"class_name": "Int", "config": {"name": "units_layer_0", "default": null, "conditions": [], "min_value": 1, "max_value": 145, "step": 5, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "num_layers", "default": null, "conditions": [], "min_value": 1, "max_value": 2, "step": 1, "sampling": "linear"}}, {"class_name": "Int", "config": {"name": "units_layer_1", "default": null, "conditions": [], "min_value": 1, "max_value": 145, "step": 5, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation_layer_1", "default": "relu", "conditions": [], "values": ["relu", "leaky_relu", "tanh", "elu", "selu", "exponential", "softmax", "softplus"], "ordered": false}}, {"class_name": "Int", "config": {"name": "units_layer_2", "default": null, "conditions": [], "min_value": 1, "max_value": 145, "step": 5, "sampling": "linear"}}, {"class_name": "Choice", "config": {"name": "activation_layer_2", "default": "relu", "conditions": [], "values": ["relu", "leaky_relu", "tanh", "elu", "selu", "exponential", "softmax", "softplus"], "ordered": false}}], "values": {"activation_layer_0": "leaky_relu", "units_layer_0": 136, "num_layers": 2, "units_layer_1": 41, "activation_layer_1": "elu", "units_layer_2": 56, "activation_layer_2": "softmax", "tuner/epochs": 7, "tuner/initial_epoch": 0, "tuner/bracket": 1, "tuner/round": 0}}, "metrics": {"metrics": {}}, "score": null, "best_step": 0, "status": "FAILED", "message": "Traceback (most recent call last):\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n    self._run_and_update_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n    results = self.run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n    return super().run_trial(trial, *fit_args, **fit_kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n    obj_value = self._build_and_fit_model(trial, *args, **copied_kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n    results = self.hypermodel.fit(hp, model, *args, **kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n    return model.fit(*args, **kwargs)\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 70, in error_handler\n    raise e.with_traceback(filtered_tb) from None\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/tensorflow/python/eager/execute.py\", line 53, in quick_execute\n    tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,\ntensorflow.python.framework.errors_impl.InvalidArgumentError: Graph execution error:\n\nDetected at node AssignAddVariableOp defined at (most recent call last):\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/runpy.py\", line 196, in _run_module_as_main\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/runpy.py\", line 86, in _run_code\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel_launcher.py\", line 17, in <module>\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/traitlets/config/application.py\", line 992, in launch_instance\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelapp.py\", line 736, in start\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/tornado/platform/asyncio.py\", line 195, in start\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/asyncio/base_events.py\", line 603, in run_forever\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/asyncio/base_events.py\", line 1909, in _run_once\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/asyncio/events.py\", line 80, in _run\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 516, in dispatch_queue\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 505, in process_one\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 412, in dispatch_shell\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/kernelbase.py\", line 740, in execute_request\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/ipkernel.py\", line 422, in do_execute\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/ipykernel/zmqshell.py\", line 546, in run_cell\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3024, in run_cell\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3079, in _run_cell\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/async_helpers.py\", line 129, in _pseudo_sync_runner\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3284, in run_cell_async\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3466, in run_ast_nodes\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/IPython/core/interactiveshell.py\", line 3526, in run_code\n\n  File \"/var/folders/ty/2_dklc2s4llcw6m5n02lv30h0000gn/T/ipykernel_24743/1767971879.py\", line 2, in <module>\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 233, in search\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 273, in _try_run_and_update_trial\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/base_tuner.py\", line 238, in _run_and_update_trial\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/tuners/hyperband.py\", line 427, in run_trial\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 314, in run_trial\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/tuner.py\", line 233, in _build_and_fit_model\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras_tuner/src/engine/hypermodel.py\", line 149, in fit\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/traceback_utils.py\", line 65, in error_handler\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1807, in fit\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1401, in train_function\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1384, in step_function\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1373, in run_step\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1151, in train_step\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/training.py\", line 1209, in compute_loss\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/engine/compile_utils.py\", line 329, in __call__\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/utils/metrics_utils.py\", line 77, in decorated\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/metrics/base_metric.py\", line 140, in update_state_fn\n\n  File \"/Users/alyssahondrade/anaconda3/envs/dev/lib/python3.10/site-packages/keras/src/metrics/base_metric.py\", line 528, in update_state\n\nCannot update variable with shape [] using a Tensor with shape [0], shapes must be equal.\n\t [[{{node AssignAddVariableOp}}]] [Op:__inference_train_function_1408968]\n"}